use chrono::{DateTime, Utc};
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::{ExchangeId, OrderSide};

/// Trade action recommended by the AI.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SignalAction {
    StrongBuy,
    Buy,
    Hold,
    Sell,
    StrongSell,
}

/// Source of the trading signal.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SignalSource {
    Technical,
    Sentiment,
    Pattern,
    AiDecision,
    Combined,
    Manual,
}

/// A trading signal generated by the AI analysis engine.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TradingSignal {
    pub id: Uuid,
    pub exchange: ExchangeId,
    pub symbol: String,
    pub timeframe: String,
    pub action: SignalAction,
    pub source: SignalSource,
    pub confidence: f64,
    pub entry_price: Option<Decimal>,
    pub stop_loss: Option<Decimal>,
    pub take_profit: Option<Decimal>,
    pub position_size_pct: Option<f64>,
    pub risk_reward_ratio: Option<f64>,
    pub reasoning: String,
    pub indicators: SignalIndicators,
    pub created_at: DateTime<Utc>,
    pub expires_at: Option<DateTime<Utc>>,
    pub executed: bool,
}

impl TradingSignal {
    /// Create a new trading signal.
    pub fn new(
        exchange: ExchangeId,
        symbol: &str,
        timeframe: &str,
        action: SignalAction,
        source: SignalSource,
        confidence: f64,
        reasoning: &str,
    ) -> Self {
        Self {
            id: Uuid::new_v4(),
            exchange,
            symbol: symbol.to_string(),
            timeframe: timeframe.to_string(),
            action,
            source,
            confidence: confidence.clamp(0.0, 1.0),
            entry_price: None,
            stop_loss: None,
            take_profit: None,
            position_size_pct: None,
            risk_reward_ratio: None,
            reasoning: reasoning.to_string(),
            indicators: SignalIndicators::default(),
            created_at: Utc::now(),
            expires_at: None,
            executed: false,
        }
    }

    /// Check if signal is actionable (buy or sell, not hold).
    pub fn is_actionable(&self) -> bool {
        matches!(
            self.action,
            SignalAction::Buy | SignalAction::StrongBuy | SignalAction::Sell | SignalAction::StrongSell
        )
    }

    /// Get the order side for this signal.
    pub fn order_side(&self) -> Option<OrderSide> {
        match self.action {
            SignalAction::Buy | SignalAction::StrongBuy => Some(OrderSide::Buy),
            SignalAction::Sell | SignalAction::StrongSell => Some(OrderSide::Sell),
            SignalAction::Hold => None,
        }
    }

    /// Check if signal has expired.
    pub fn is_expired(&self) -> bool {
        if let Some(expires) = self.expires_at {
            Utc::now() > expires
        } else {
            false
        }
    }
}

/// Technical indicator values at the time of signal generation.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct SignalIndicators {
    pub rsi: Option<f64>,
    pub macd: Option<MacdValues>,
    pub ema_short: Option<f64>,
    pub ema_long: Option<f64>,
    pub bollinger: Option<BollingerValues>,
    pub atr: Option<f64>,
    pub volume_ratio: Option<f64>,
    pub stochastic_k: Option<f64>,
    pub stochastic_d: Option<f64>,
    pub sentiment_score: Option<f64>,
    pub pattern_name: Option<String>,
    pub pattern_confidence: Option<f64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MacdValues {
    pub macd: f64,
    pub signal: f64,
    pub histogram: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BollingerValues {
    pub upper: f64,
    pub middle: f64,
    pub lower: f64,
    pub bandwidth: f64,
}

/// AI analysis result from Grok.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnalysisResult {
    pub id: Uuid,
    pub symbol: String,
    pub exchange: ExchangeId,
    pub timestamp: DateTime<Utc>,
    pub technical_summary: String,
    pub sentiment_summary: String,
    pub pattern_summary: String,
    pub overall_analysis: String,
    pub signal: TradingSignal,
    pub grok_model_used: String,
    pub tokens_used: u32,
}

/// Dashboard summary for mobile app.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DashboardSummary {
    pub total_balance: Decimal,
    pub available_balance: Decimal,
    pub daily_pnl: Decimal,
    pub daily_pnl_pct: f64,
    pub weekly_pnl: Decimal,
    pub weekly_pnl_pct: f64,
    pub total_pnl: Decimal,
    pub total_pnl_pct: f64,
    pub open_positions_count: usize,
    pub active_signals_count: usize,
    pub win_rate: f64,
    pub trading_mode: String,
    pub is_trading_active: bool,
    pub last_analysis_at: Option<DateTime<Utc>>,
}

/// Performance metrics over a time period.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PerformanceMetrics {
    pub period: String,
    pub total_trades: u32,
    pub winning_trades: u32,
    pub losing_trades: u32,
    pub win_rate: f64,
    pub total_pnl: Decimal,
    pub max_drawdown: f64,
    pub sharpe_ratio: Option<f64>,
    pub profit_factor: Option<f64>,
    pub average_win: Decimal,
    pub average_loss: Decimal,
    pub largest_win: Decimal,
    pub largest_loss: Decimal,
    pub average_holding_time_mins: f64,
}
