-- AI Trading Platform - Database Schema
-- Uses TimescaleDB for time-series data optimization

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS timescaledb;

-- ============================================================================
-- CANDLES (OHLCV historical data) — Core time-series table
-- ============================================================================
CREATE TABLE IF NOT EXISTS candles (
    open_time TIMESTAMPTZ NOT NULL,
    symbol VARCHAR(32) NOT NULL,
    exchange VARCHAR(16) NOT NULL,
    timeframe VARCHAR(8) NOT NULL,
    close_time TIMESTAMPTZ NOT NULL,
    open DECIMAL(24, 8) NOT NULL,
    high DECIMAL(24, 8) NOT NULL,
    low DECIMAL(24, 8) NOT NULL,
    close DECIMAL(24, 8) NOT NULL,
    volume DECIMAL(24, 8) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Convert to TimescaleDB hypertable — this is the key optimization
-- Automatically partitions data by time (default 7-day chunks)
SELECT create_hypertable('candles', 'open_time',
    chunk_time_interval => INTERVAL '7 days',
    if_not_exists => TRUE
);

-- Composite index for the most common query: candles for a symbol + timeframe
CREATE INDEX IF NOT EXISTS idx_candles_symbol_tf_time
    ON candles (symbol, exchange, timeframe, open_time DESC);

-- Unique constraint to prevent duplicate candles
CREATE UNIQUE INDEX IF NOT EXISTS idx_candles_unique
    ON candles (symbol, exchange, timeframe, open_time);

-- Enable TimescaleDB compression on candles older than 7 days
-- Compresses storage ~90%, critical for storing millions of candles
ALTER TABLE candles SET (
    timescaledb.compress,
    timescaledb.compress_segmentby = 'symbol, exchange, timeframe',
    timescaledb.compress_orderby = 'open_time DESC'
);

SELECT add_compression_policy('candles', INTERVAL '7 days', if_not_exists => TRUE);

-- Auto-delete candles older than 1 year (configurable)
SELECT add_retention_policy('candles', INTERVAL '365 days', if_not_exists => TRUE);

-- ============================================================================
-- CONTINUOUS AGGREGATES — Pre-computed rollups for fast dashboard/charting
-- ============================================================================

-- Hourly OHLCV summary (refreshes every 5 minutes)
CREATE MATERIALIZED VIEW IF NOT EXISTS candles_1h
WITH (timescaledb.continuous) AS
SELECT
    time_bucket('1 hour', open_time) AS bucket,
    symbol,
    exchange,
    FIRST(open, open_time) AS open,
    MAX(high) AS high,
    MIN(low) AS low,
    LAST(close, open_time) AS close,
    SUM(volume) AS volume,
    COUNT(*) AS candle_count
FROM candles
WHERE timeframe = '1m' OR timeframe = '5m'
GROUP BY bucket, symbol, exchange
WITH NO DATA;

SELECT add_continuous_aggregate_policy('candles_1h',
    start_offset => INTERVAL '3 hours',
    end_offset => INTERVAL '1 hour',
    schedule_interval => INTERVAL '5 minutes',
    if_not_exists => TRUE
);

-- Daily OHLCV summary (refreshes every 30 minutes)
CREATE MATERIALIZED VIEW IF NOT EXISTS candles_1d
WITH (timescaledb.continuous) AS
SELECT
    time_bucket('1 day', open_time) AS bucket,
    symbol,
    exchange,
    FIRST(open, open_time) AS open,
    MAX(high) AS high,
    MIN(low) AS low,
    LAST(close, open_time) AS close,
    SUM(volume) AS volume,
    COUNT(*) AS candle_count
FROM candles
WHERE timeframe = '1h' OR timeframe = '1m'
GROUP BY bucket, symbol, exchange
WITH NO DATA;

SELECT add_continuous_aggregate_policy('candles_1d',
    start_offset => INTERVAL '3 days',
    end_offset => INTERVAL '1 day',
    schedule_interval => INTERVAL '30 minutes',
    if_not_exists => TRUE
);

-- ============================================================================
-- TRADE SIGNALS — Generated by AI
-- ============================================================================
CREATE TABLE IF NOT EXISTS signals (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    exchange VARCHAR(16) NOT NULL,
    symbol VARCHAR(32) NOT NULL,
    timeframe VARCHAR(8) NOT NULL,
    action VARCHAR(16) NOT NULL,
    source VARCHAR(16) NOT NULL,
    confidence DOUBLE PRECISION NOT NULL,
    entry_price DECIMAL(24, 8),
    stop_loss DECIMAL(24, 8),
    take_profit DECIMAL(24, 8),
    position_size_pct DOUBLE PRECISION,
    risk_reward_ratio DOUBLE PRECISION,
    reasoning TEXT NOT NULL,
    indicators JSONB,
    executed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    expires_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_signals_symbol ON signals (symbol, exchange);
CREATE INDEX IF NOT EXISTS idx_signals_created ON signals (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_signals_action ON signals (action);
CREATE INDEX IF NOT EXISTS idx_signals_pending ON signals (executed, created_at DESC) WHERE executed = FALSE;

-- ============================================================================
-- EXECUTED TRADES
-- ============================================================================
CREATE TABLE IF NOT EXISTS trades (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    exchange VARCHAR(16) NOT NULL,
    symbol VARCHAR(32) NOT NULL,
    side VARCHAR(8) NOT NULL,
    quantity DECIMAL(24, 8) NOT NULL,
    entry_price DECIMAL(24, 8) NOT NULL,
    exit_price DECIMAL(24, 8),
    fees DECIMAL(24, 8) DEFAULT 0,
    realized_pnl DECIMAL(24, 8),
    signal_id UUID REFERENCES signals(id),
    signal_confidence DOUBLE PRECISION,
    opened_at TIMESTAMPTZ DEFAULT NOW(),
    closed_at TIMESTAMPTZ,
    close_reason VARCHAR(32)
);

CREATE INDEX IF NOT EXISTS idx_trades_symbol ON trades (symbol, exchange);
CREATE INDEX IF NOT EXISTS idx_trades_opened ON trades (opened_at DESC);
CREATE INDEX IF NOT EXISTS idx_trades_open_only ON trades (opened_at DESC) WHERE closed_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_trades_pnl ON trades (realized_pnl) WHERE realized_pnl IS NOT NULL;

-- ============================================================================
-- OPEN POSITIONS
-- ============================================================================
CREATE TABLE IF NOT EXISTS positions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    exchange VARCHAR(16) NOT NULL,
    symbol VARCHAR(32) NOT NULL,
    side VARCHAR(8) NOT NULL,
    quantity DECIMAL(24, 8) NOT NULL,
    entry_price DECIMAL(24, 8) NOT NULL,
    current_price DECIMAL(24, 8),
    stop_loss DECIMAL(24, 8),
    take_profit DECIMAL(24, 8),
    unrealized_pnl DECIMAL(24, 8) DEFAULT 0,
    unrealized_pnl_pct DOUBLE PRECISION DEFAULT 0,
    fees_paid DECIMAL(24, 8) DEFAULT 0,
    signal_id UUID REFERENCES signals(id),
    opened_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_positions_exchange ON positions (exchange);

-- ============================================================================
-- AI ANALYSIS LOGS
-- ============================================================================
CREATE TABLE IF NOT EXISTS analysis_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    symbol VARCHAR(32) NOT NULL,
    exchange VARCHAR(16) NOT NULL,
    technical_summary TEXT,
    sentiment_summary TEXT,
    pattern_summary TEXT,
    overall_analysis TEXT,
    signal_id UUID REFERENCES signals(id),
    grok_model VARCHAR(32),
    tokens_used INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_analysis_symbol ON analysis_logs (symbol, exchange);
CREATE INDEX IF NOT EXISTS idx_analysis_created ON analysis_logs (created_at DESC);

-- ============================================================================
-- ACCOUNT SNAPSHOTS — Portfolio tracking over time (hypertable)
-- ============================================================================
CREATE TABLE IF NOT EXISTS account_snapshots (
    snapshot_at TIMESTAMPTZ NOT NULL,
    exchange VARCHAR(16) NOT NULL,
    total_usd DECIMAL(24, 8),
    balances JSONB
);

SELECT create_hypertable('account_snapshots', 'snapshot_at',
    chunk_time_interval => INTERVAL '30 days',
    if_not_exists => TRUE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_snapshots_unique
    ON account_snapshots (exchange, snapshot_at);

-- Compress snapshots older than 30 days
ALTER TABLE account_snapshots SET (
    timescaledb.compress,
    timescaledb.compress_segmentby = 'exchange',
    timescaledb.compress_orderby = 'snapshot_at DESC'
);

SELECT add_compression_policy('account_snapshots', INTERVAL '30 days', if_not_exists => TRUE);

-- ============================================================================
-- BACKTEST RESULTS — Store backtest runs
-- ============================================================================
CREATE TABLE IF NOT EXISTS backtest_results (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    symbol VARCHAR(32) NOT NULL,
    exchange VARCHAR(16) NOT NULL,
    timeframe VARCHAR(8) NOT NULL,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    initial_balance DECIMAL(24, 8) NOT NULL,
    final_balance DECIMAL(24, 8) NOT NULL,
    total_return_pct DOUBLE PRECISION,
    max_drawdown_pct DOUBLE PRECISION,
    sharpe_ratio DOUBLE PRECISION,
    sortino_ratio DOUBLE PRECISION,
    win_rate_pct DOUBLE PRECISION,
    profit_factor DOUBLE PRECISION,
    total_trades INTEGER,
    winning_trades INTEGER,
    losing_trades INTEGER,
    total_fees DECIMAL(24, 8),
    config JSONB NOT NULL,
    metrics JSONB NOT NULL,
    equity_curve DOUBLE PRECISION[],
    total_candles INTEGER,
    signals_generated INTEGER,
    signals_executed INTEGER,
    duration_secs DOUBLE PRECISION,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_backtest_symbol ON backtest_results (symbol, exchange);
CREATE INDEX IF NOT EXISTS idx_backtest_created ON backtest_results (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_backtest_performance ON backtest_results (total_return_pct DESC);

-- ============================================================================
-- USER SETTINGS
-- ============================================================================
CREATE TABLE IF NOT EXISTS settings (
    key VARCHAR(64) PRIMARY KEY,
    value JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert default settings
INSERT INTO settings (key, value) VALUES
    ('trading_mode', '"manual"'),
    ('watched_symbols', '["BTCUSDT", "ETHUSDT", "SOLUSDT"]'),
    ('risk_params', '{"max_position_size_pct": 5.0, "max_daily_loss_pct": 3.0, "max_concurrent_positions": 5}')
ON CONFLICT (key) DO NOTHING;
